services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
          NEXT_PUBLIC_API_URL: ""
    container_name: my-project-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-project-backend
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: mysql:8.4
    container_name: my-project-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: